package net.droingo.decor.client.animation;

import net.droingo.decor.content.DecorContainerBlockEntity;
import net.droingo.decor.content.TinyDecorItem;

import java.util.Map;
import java.util.WeakHashMap;

/**
 * Client-side one-shot pulses generated by bobblehead interactions.
 *
 * Weak keys ensure unloaded block entities are not retained.
 */
public final class BobbleheadInteractionPulses {
    private static final Map<
            DecorContainerBlockEntity,
            boolean[]
            > PULSES = new WeakHashMap<>();

    private BobbleheadInteractionPulses() {
    }

    public static void trigger(
            DecorContainerBlockEntity container,
            int slot
    ) {
        if (container == null || slot < 0 || slot >= TinyDecorItem.SLOT_COUNT) {
            return;
        }

        boolean[] slots = PULSES.computeIfAbsent(
                container,
                ignored -> new boolean[TinyDecorItem.SLOT_COUNT]
        );

        slots[slot] = true;
    }

    public static boolean consume(
            DecorContainerBlockEntity container,
            int slot
    ) {
        if (container == null || slot < 0 || slot >= TinyDecorItem.SLOT_COUNT) {
            return false;
        }

        boolean[] slots = PULSES.get(container);

        if (slots == null || !slots[slot]) {
            return false;
        }

        slots[slot] = false;
        return true;
    }
}